/**
* Task: Each new term in the Fibonacci sequence is generated by adding the
* previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
* nth term, find the sum of the even-valued terms.
*/
function fiboEvenSum(n) {
  let arr = [1, 1, 2];
  for (let i = 3; arr.length < n + 2; i++) {
    arr.push(arr[i - 1] + arr[i - 2]);
  }

  return arr.filter(x => x % 2 === 0).reduce((x, y) => x + y);
}

fiboEvenSum(10);
